@HOST = http://localhost:8000
@id = 6233a141aa8b31fa1e04d183

### GET /health-check
GET {{HOST}}/health-check


### GET /users
GET {{HOST}}/users


### GET /users/:id
GET {{HOST}}/users/{{id}}


### POST /users
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "Yury",
  "email": "yury@example.com",
  "role": "admin"
}


### PATCH /users/:ID
PATCH {{HOST}}/users/{{id}}
Content-Type: application/json

{
  "name": "Yury",
  "role": "user"
}


### PUT /users/:ID
PUT {{HOST}}/users/{{id}}
Content-Type: application/json

{
  "name": "Yury",
  "email": "yury@example.com"
}


### DELETE /users/:id
DELETE {{HOST}}/users/{{id}}