version: "3.8"
services:

  app:
    image: denoland/deno:alpine-1.18.0
    command: deno run --allow-net --watch app/app.ts
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    working_dir: /usr/src