version: "3.8"
services:

  app:
    image: denoland/deno:alpine-1.18.0
    command: deno run --allow-net --watch app/app.ts
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    links:
      - db
    working_dir: /usr/src

  db:
    image: mongo:4.4-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      driver: none